name: hadas
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.8.10
  - readline=8.0
  - pip:
    - argparse==1.4.0
    - autograd==1.3
    - cython==0.29.16
    - docutils==0.17
    - joblib==1.0.1
    - paramiko==2.7.2
    - matplotlib==3.4.3
    - numpy==1.18.0
    - packaging==20.9
    - pandas==1.2.2
    - pymoo==0.4.0
    - pymop==0.2.4
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - urllib3==1.25.19
    - torch==1.11.0
    - torchvision==0.12.0
